// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdggcHSDpqUNN-ZCwZ54lkODsykxk_k2c',
    appId: '1:819477396776:web:24c41183ce703adfb4641d',
    messagingSenderId: '819477396776',
    projectId: 'onebytefoodscollab-50a6f',
    authDomain: 'onebytefoodscollab-50a6f.firebaseapp.com',
    storageBucket: 'onebytefoodscollab-50a6f.appspot.com',
    measurementId: 'G-5ZHYR9229W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4pmF6CbWZ8zTLgXUKhMJffHxLb0sSBcY',
    appId: '1:819477396776:android:b7f1dc993ae5497db4641d',
    messagingSenderId: '819477396776',
    projectId: 'onebytefoodscollab-50a6f',
    storageBucket: 'onebytefoodscollab-50a6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCbE_-Wnc-KUIPDlvGcUkcSx4aE7R1nzE',
    appId: '1:819477396776:ios:74b574e92e1399d8b4641d',
    messagingSenderId: '819477396776',
    projectId: 'onebytefoodscollab-50a6f',
    storageBucket: 'onebytefoodscollab-50a6f.appspot.com',
    androidClientId: '819477396776-bcp259ai1889kh3i538od4i6ru7d7qtv.apps.googleusercontent.com',
    iosClientId: '819477396776-l1ct5u9avp9gb64e8q95irmh44nklcjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneByteFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCbE_-Wnc-KUIPDlvGcUkcSx4aE7R1nzE',
    appId: '1:819477396776:ios:74b574e92e1399d8b4641d',
    messagingSenderId: '819477396776',
    projectId: 'onebytefoodscollab-50a6f',
    storageBucket: 'onebytefoodscollab-50a6f.appspot.com',
    androidClientId: '819477396776-bcp259ai1889kh3i538od4i6ru7d7qtv.apps.googleusercontent.com',
    iosClientId: '819477396776-l1ct5u9avp9gb64e8q95irmh44nklcjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneByteFoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdggcHSDpqUNN-ZCwZ54lkODsykxk_k2c',
    appId: '1:819477396776:web:2f457bd3d1c57c97b4641d',
    messagingSenderId: '819477396776',
    projectId: 'onebytefoodscollab-50a6f',
    authDomain: 'onebytefoodscollab-50a6f.firebaseapp.com',
    storageBucket: 'onebytefoodscollab-50a6f.appspot.com',
    measurementId: 'G-YL9MJN2H2H',
  );

}